# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  armv7: ghcr.io/hassio-addons/debian-base/armv7:5.0.0
  armhf: ghcr.io/hassio-addons/debian-base/armhf:5.0.0
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:5.0.0
  amd64: ghcr.io/hassio-addons/debian-base/amd64:5.0.0
  i386: ghcr.io/hassio-addons/debian-base/i386:5.0.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: amridm2mqtt add-on"
  org.opencontainers.image.description: "Send AMR/ERT Power Meter Data Over MQTT"
  org.opencontainers.image.source: "https://github.com/jaredhobbs/ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
