# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: amridm2mqtt add-on
version: "1.0.0"
slug: amridm2mqtt
description: Send AMR/ERT Power Meter Data Over MQTT
url: "https://github.com/jaredhobbs/ha-addons/tree/main/amridm2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
advanced: true
usb: true
services:
  - mqtt:need
options:
  WATCHED_METERS: []
  WH_MULTIPLIER: 1000
  READINGS_PER_HOUR: 12
  DEBUG: ""
schema:
  WATCHED_METERS: [int]
  WH_MULTIPLIER: int
  READINGS_PER_HOUR: int
  DEBUG: str
image: "ghcr.io/home-assistant/{arch}-addon-amridm2mqtt"
